// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetServer.Data;

#nullable disable

namespace NetServer.DAta1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206165528_AddKycDocumentTable")]
    partial class AddKycDocumentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetServer.Data.Models.KycDocument", b =>
                {
                    b.Property<Guid>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocId");

                    b.HasIndex("UserId");

                    b.ToTable("KycDocument");

                    b.HasData(
                        new
                        {
                            DocId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            DocumentNumber = "A12345678",
                            ExpiryDate = new DateTime(2030, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "A12345678",
                            Status = "Pending",
                            Type = "Passport",
                            UploadedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.OrderBook", b =>
                {
                    b.Property<Guid>("OrderBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderBookId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderBookTable");

                    b.HasData(
                        new
                        {
                            OrderBookId = new Guid("658e7a5c-6e02-4d31-a098-ee6b3dfedbb4"),
                            Amount = 0.1m,
                            OrderId = new Guid("23279bc0-3f81-4bbd-b44e-b61b92b01ba4"),
                            Price = 50000.0m,
                            Symbol = "BTCUSD",
                            Timestamp = new DateTime(2025, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.OrdersTable", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("23279bc0-3f81-4bbd-b44e-b61b92b01ba4"),
                            Amount = 0.1m,
                            CreatedAt = new DateTime(2025, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = 0,
                            Price = 50000.0m,
                            Symbol = "BTCUSD",
                            TypeOfOrder = 0,
                            UserId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.TradesTable", b =>
                {
                    b.Property<Guid>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<Guid>("BuyOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("SellOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TradeId");

                    b.HasIndex("BuyOrderId");

                    b.HasIndex("SellOrderId");

                    b.ToTable("TradesTable");

                    b.HasData(
                        new
                        {
                            TradeId = new Guid("f3c9a1b2-4d5e-6789-abcd-0123456789ab"),
                            Amount = 0.5,
                            BuyOrderId = new Guid("23279bc0-3f81-4bbd-b44e-b61b92b01ba4"),
                            Price = 70000.0m,
                            TimeStamp = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alice@email.com",
                            IsBanned = false,
                            PasswordHash = "Password",
                            Status = 1,
                            UserName = "Alice"
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.WalletTable", b =>
                {
                    b.Property<Guid>("WalletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WalletTableWalletID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WalletID");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletTableWalletID");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            WalletID = new Guid("3249fc5e-7cd9-49ab-87db-c581a24f0938"),
                            Addres = "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
                            Balance = 1.5m,
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "BTC",
                            Status = "Active",
                            UserId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.KycDocument", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetServer.Data.Models.OrderBook", b =>
                {
                    b.HasOne("NetServer.Data.Models.OrdersTable", "Order")
                        .WithOne("OrderBook")
                        .HasForeignKey("NetServer.Data.Models.OrderBook", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("NetServer.Data.Models.OrdersTable", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetServer.Data.Models.TradesTable", b =>
                {
                    b.HasOne("NetServer.Data.Models.OrdersTable", "BuyOrder")
                        .WithMany()
                        .HasForeignKey("BuyOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetServer.Data.Models.OrdersTable", "SellOrder")
                        .WithMany()
                        .HasForeignKey("SellOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BuyOrder");

                    b.Navigation("SellOrder");
                });

            modelBuilder.Entity("NetServer.Data.Models.WalletTable", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetServer.Data.Models.WalletTable", null)
                        .WithMany("Wallets")
                        .HasForeignKey("WalletTableWalletID");
                });

            modelBuilder.Entity("NetServer.Data.Models.OrdersTable", b =>
                {
                    b.Navigation("OrderBook")
                        .IsRequired();
                });

            modelBuilder.Entity("NetServer.Data.Models.WalletTable", b =>
                {
                    b.Navigation("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
