// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetServer.Data;

#nullable disable

namespace NetServer.DAta1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204184058_SecondTable")]
    partial class SecondTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetServer.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alice@email.com",
                            IsBanned = false,
                            PasswordHash = "Password",
                            Status = 1,
                            UserName = "Alice"
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.WalletTable", b =>
                {
                    b.Property<Guid>("WalletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WalletTableWalletID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WalletID");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletTableWalletID");

                    b.ToTable("WalletTable");

                    b.HasData(
                        new
                        {
                            WalletID = new Guid("3249fc5e-7cd9-49ab-87db-c581a24f0938"),
                            Addres = "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
                            Balance = 1.5m,
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = "BTC",
                            Status = "Active",
                            UserId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.WalletTable", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetServer.Data.Models.WalletTable", null)
                        .WithMany("Wallets")
                        .HasForeignKey("WalletTableWalletID");
                });

            modelBuilder.Entity("NetServer.Data.Models.WalletTable", b =>
                {
                    b.Navigation("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
