// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetServer.DB_Context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DB_COntext))]
    partial class DB_COntextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditLogTableNameSpace.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId1");

                    b.ToTable("AuditLogTable");
                });

            modelBuilder.Entity("BlockchainEventtablenNameSpace.BlockchainEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TxHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("BlockchainEventtable");
                });

            modelBuilder.Entity("ExchangeTransactionNameSpace.ExchangeTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlockchainEventEventId")
                        .HasColumnType("int");

                    b.Property<string>("BlockchainTransactionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeOfTransaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.HasIndex("BlockchainEventEventId");

                    b.HasIndex("UserID");

                    b.ToTable("TransactionsTable");
                });

            modelBuilder.Entity("FeeTableNameSpace.Fee", b =>
                {
                    b.Property<Guid>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MakerFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TakerFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FeeId");

                    b.ToTable("FeesTable");
                });

            modelBuilder.Entity("KycDocumentTableNameSpace.KycDocument", b =>
                {
                    b.Property<Guid>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("DocId");

                    b.HasIndex("UserId1");

                    b.ToTable("KycDocumenTable");
                });

            modelBuilder.Entity("OrderBookTablenamepsace.OrderBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrderBookTable");
                });

            modelBuilder.Entity("OrdersTablenamepsace.Data.OrdersTable", b =>
                {
                    b.Property<int>("Order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Order_Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type_Of_Order")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Order_Id");

                    b.HasIndex("UserId");

                    b.ToTable("OrdersTable");
                });

            modelBuilder.Entity("ReferralTable.Referral", b =>
                {
                    b.Property<int>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferralId"));

                    b.Property<decimal>("BonusAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReferredId")
                        .HasColumnType("int");

                    b.Property<int>("ReferrerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ReferralId");

                    b.HasIndex("ReferredId");

                    b.HasIndex("ReferrerId");

                    b.ToTable("ReferralsTable");
                });

            modelBuilder.Entity("SessionTableNameSpace.SessionTable", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId1");

                    b.ToTable("SessionTable");
                });

            modelBuilder.Entity("TradesTableNameSpace.TradesTable", b =>
                {
                    b.Property<int>("Trade_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trade_ID"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("Buy_Order_Id")
                        .HasColumnType("int");

                    b.Property<int?>("OrderBookId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderBookId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sell_Order_Id")
                        .HasColumnType("int");

                    b.Property<double>("timestamp")
                        .HasColumnType("float");

                    b.HasKey("Trade_ID");

                    b.HasIndex("Buy_Order_Id");

                    b.HasIndex("OrderBookId");

                    b.HasIndex("OrderBookId1");

                    b.HasIndex("Sell_Order_Id");

                    b.ToTable("TradesTable");
                });

            modelBuilder.Entity("UserNameSpace.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WalletTableNameSpace.WalletTable", b =>
                {
                    b.Property<int>("WalletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletID"));

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WalletID");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("AuditLogTableNameSpace.AuditLog", b =>
                {
                    b.HasOne("UserNameSpace.Data.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExchangeTransactionNameSpace.ExchangeTransaction", b =>
                {
                    b.HasOne("BlockchainEventtablenNameSpace.BlockchainEvent", "BlockchainEvent")
                        .WithMany("ExchangeTransaction")
                        .HasForeignKey("BlockchainEventEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserNameSpace.Data.User", "User")
                        .WithMany("ExchangeTransaction")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockchainEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KycDocumentTableNameSpace.KycDocument", b =>
                {
                    b.HasOne("UserNameSpace.Data.User", "User")
                        .WithMany("KycDocuments")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrdersTablenamepsace.Data.OrdersTable", b =>
                {
                    b.HasOne("UserNameSpace.Data.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReferralTable.Referral", b =>
                {
                    b.HasOne("UserNameSpace.Data.User", "Referred")
                        .WithMany("ReferralsReceived")
                        .HasForeignKey("ReferredId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserNameSpace.Data.User", "Referrer")
                        .WithMany("ReferralsMade")
                        .HasForeignKey("ReferrerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Referred");

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("SessionTableNameSpace.SessionTable", b =>
                {
                    b.HasOne("UserNameSpace.Data.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradesTableNameSpace.TradesTable", b =>
                {
                    b.HasOne("OrdersTablenamepsace.Data.OrdersTable", "BuyOrder")
                        .WithMany("TradesAsBuyOrder")
                        .HasForeignKey("Buy_Order_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderBookTablenamepsace.OrderBook", null)
                        .WithMany("TradesAsBuyOrder")
                        .HasForeignKey("OrderBookId");

                    b.HasOne("OrderBookTablenamepsace.OrderBook", null)
                        .WithMany("TradesAsSellOrder")
                        .HasForeignKey("OrderBookId1");

                    b.HasOne("OrdersTablenamepsace.Data.OrdersTable", "SellOrder")
                        .WithMany("TradesAsSellOrder")
                        .HasForeignKey("Sell_Order_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuyOrder");

                    b.Navigation("SellOrder");
                });

            modelBuilder.Entity("WalletTableNameSpace.WalletTable", b =>
                {
                    b.HasOne("UserNameSpace.Data.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlockchainEventtablenNameSpace.BlockchainEvent", b =>
                {
                    b.Navigation("ExchangeTransaction");
                });

            modelBuilder.Entity("OrderBookTablenamepsace.OrderBook", b =>
                {
                    b.Navigation("TradesAsBuyOrder");

                    b.Navigation("TradesAsSellOrder");
                });

            modelBuilder.Entity("OrdersTablenamepsace.Data.OrdersTable", b =>
                {
                    b.Navigation("TradesAsBuyOrder");

                    b.Navigation("TradesAsSellOrder");
                });

            modelBuilder.Entity("UserNameSpace.Data.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ExchangeTransaction");

                    b.Navigation("KycDocuments");

                    b.Navigation("Orders");

                    b.Navigation("ReferralsMade");

                    b.Navigation("ReferralsReceived");

                    b.Navigation("Sessions");

                    b.Navigation("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
