// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetServer.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetServer.DAta1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309170010_AddBankAccounts")]
    partial class AddBankAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetServer.Data.Models.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            LogId = new Guid("23116bf4-42b9-4d37-8569-f8a21e4b5265"),
                            Action = "User Login",
                            Details = "User Alice logged in successfully.",
                            Timestamp = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.BankAccountTable", b =>
                {
                    b.Property<Guid>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SwiftCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("BankAccountId");

                    b.HasIndex("UserId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("NetServer.Data.Models.BlockchainEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExchangeTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TxHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.HasIndex("ExchangeTransactionId");

                    b.ToTable("BlockchainEvents");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("9651ad0b-80cc-4993-90d5-611317255952"),
                            EventType = "Deposit",
                            ExchangeTransactionId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890"),
                            Status = "Confirmed",
                            Timestamp = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            TxHash = "2d6ea11f-071b-45db-8cc1-e4a31e7ae808"
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.CreditCardDetailsTable", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardLast4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("CreditCardDetails");
                });

            modelBuilder.Entity("NetServer.Data.Models.ExchangeTransaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("BlockchainTransactionHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TypeOfTransaction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionID");

                    b.HasIndex("UserID");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionID = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890"),
                            Amount = 0.5m,
                            BlockchainTransactionHash = "0000000000000000000a7b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4",
                            Currency = "BTC",
                            Status = "Completed",
                            TimeStamp = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            TypeOfTransaction = "Deposit",
                            UserID = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.FAQ", b =>
                {
                    b.Property<Guid>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("RepliedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FaqId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RepliedByUserId");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            FaqId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890"),
                            Answer = "To create an account, click on the Sign Up button and fill in the required information.",
                            AuthorId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CategoryId = new Guid("12345678-90ab-cdef-1234-567890abcdef"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublishedAt = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Question = "How to create an account?",
                            UpdatedAt = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.FeeTable", b =>
                {
                    b.Property<Guid>("FeeTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("FeeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FeeTableId");

                    b.ToTable("FeeTables");

                    b.HasData(
                        new
                        {
                            FeeTableId = new Guid("b1c2d3e4-f5a6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            FeeAmount = 0.1m,
                            FeeType = "Maker",
                            Symbol = "BTCUSD",
                            UpdatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.KycDocument", b =>
                {
                    b.Property<Guid>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryOfResidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("DocId");

                    b.HasIndex("UserId");

                    b.ToTable("KycDocuments");

                    b.HasData(
                        new
                        {
                            DocId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CountryOfResidence = "BG",
                            DateOfBirth = new DateTime(1994, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentNumber = "A12345678",
                            ExpiryDate = new DateTime(2030, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            FilePath = "/path/to/document1.pdf",
                            FullName = "Alice Example",
                            Status = "Pending",
                            Type = "Passport",
                            UploadedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.NewsTable", b =>
                {
                    b.Property<Guid>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Author")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EditedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EditedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NewsId");

                    b.HasIndex("Author");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("EditedBy");

                    b.ToTable("NewsTable", (string)null);

                    b.HasData(
                        new
                        {
                            NewsId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890"),
                            Author = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Content = "We are excited to announce the release of margin trading on our platform. Users can now trade with leverage up to 5x on selected pairs.",
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            DeletedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            DeletedOn = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            EditedOn = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublishedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "New Feature Release: Margin Trading",
                            UpdatedAt = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            NewsId = new Guid("2b3c4d5e-6f70-8910-abcd-ef1234567890"),
                            Author = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Content = "Our trading API now delivers order book snapshots with lower latency and improved depth support for BTCUSD, ETHUSD, and BNBUSD.",
                            CreatedAt = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            DeletedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            DeletedOn = new DateTime(2025, 12, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            EditedOn = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublishedAt = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "API Upgrade: Faster Order Book",
                            UpdatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            NewsId = new Guid("3c4d5e6f-7081-9210-abcd-ef1234567890"),
                            Author = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Content = "We added device-aware withdrawal checks and optional 2FA prompts for high-risk activity to better protect your account.",
                            CreatedAt = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            DeletedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            DeletedOn = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            EditedOn = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublishedAt = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Security Notice: New Withdrawal Safeguards",
                            UpdatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            NewsId = new Guid("4d5e6f70-8192-a210-abcd-ef1234567890"),
                            Author = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Content = "ALGO-EUR spot trading is now live. Review the listing details and start trading with tighter spreads.",
                            CreatedAt = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            DeletedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            DeletedOn = new DateTime(2025, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditedBy = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            EditedOn = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublishedAt = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "New Listing: ALGO-EUR Spot",
                            UpdatedAt = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.OrderBook", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrderBookId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.ToTable("OrderBookTable");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("23279bc0-3f81-4bbd-b44e-b61b92b01ba4"),
                            Amount = 0.1m,
                            OrderBookId = new Guid("6172ea6f-ebb1-4f3d-8fcb-449668255501"),
                            Price = 50000.0m,
                            Symbol = "BTCUSD",
                            Timestamp = new DateTime(2025, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.OrdersTable", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FeeTableId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeOfOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("OrderId");

                    b.HasIndex("FeeTableId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("23279bc0-3f81-4bbd-b44e-b61b92b01ba4"),
                            Amount = 0.1m,
                            CreatedAt = new DateTime(2025, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderStatus = 0,
                            Price = 50000.0m,
                            Symbol = "BTCUSD",
                            TypeOfOrder = 0,
                            UserId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.Referral", b =>
                {
                    b.Property<Guid>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BonusAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ReferredId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferrerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReferralId");

                    b.ToTable("Referrals");

                    b.HasData(
                        new
                        {
                            ReferralId = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890"),
                            BonusAmount = 50.0m,
                            ReferredId = new Guid("2b3c4d5e-6f70-8910-abcd-ef1234567890"),
                            ReferrerId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Timestamp = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.SessionTable", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            SessionId = new Guid("c0733dc5-908b-42fd-8623-8cba9e9b1b7b"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceInfo = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3",
                            ExpiresAt = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IpAddress = "127.0.0.1",
                            Token = "sample_token",
                            UserId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.TradesTable", b =>
                {
                    b.Property<Guid>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BuyOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("SellOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TradeId");

                    b.HasIndex("BuyOrderId");

                    b.HasIndex("SellOrderId");

                    b.ToTable("TradesTable");

                    b.HasData(
                        new
                        {
                            TradeId = new Guid("f3c9a1b2-4d5e-6789-abcd-0123456789ab"),
                            Amount = 0.5,
                            BuyOrderId = new Guid("23279bc0-3f81-4bbd-b44e-b61b92b01ba4"),
                            Price = 70000.0m,
                            TimeStamp = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Alice@email.com",
                            IsBanned = false,
                            Password = "Password",
                            Role = "User",
                            Status = 1,
                            UserName = "Alice"
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.WalletTable", b =>
                {
                    b.Property<Guid>("WalletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WalletTableWalletID")
                        .HasColumnType("uuid");

                    b.HasKey("WalletID");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletTableWalletID");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            WalletID = new Guid("3249fc5e-7cd9-49ab-87db-c581a24f0938"),
                            Addres = "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
                            Balance = 1.5m,
                            CreatedAt = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "BTC",
                            Status = "Active",
                            UserId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("NetServer.Data.Models.AuditLog", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetServer.Data.Models.BankAccountTable", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetServer.Data.Models.BlockchainEvent", b =>
                {
                    b.HasOne("NetServer.Data.Models.ExchangeTransaction", "ExchangeTransaction")
                        .WithMany()
                        .HasForeignKey("ExchangeTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeTransaction");
                });

            modelBuilder.Entity("NetServer.Data.Models.CreditCardDetailsTable", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("NetServer.Data.Models.CreditCardDetailsTable", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetServer.Data.Models.ExchangeTransaction", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NetServer.Data.Models.FAQ", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RepliedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NetServer.Data.Models.KycDocument", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetServer.Data.Models.NewsTable", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("Author")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("EditedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NetServer.Data.Models.OrderBook", b =>
                {
                    b.HasOne("NetServer.Data.Models.OrdersTable", "Order")
                        .WithOne("OrderBook")
                        .HasForeignKey("NetServer.Data.Models.OrderBook", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("NetServer.Data.Models.OrdersTable", b =>
                {
                    b.HasOne("NetServer.Data.Models.FeeTable", "FeeTable")
                        .WithMany("Orders")
                        .HasForeignKey("FeeTableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeTable");
                });

            modelBuilder.Entity("NetServer.Data.Models.SessionTable", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetServer.Data.Models.TradesTable", b =>
                {
                    b.HasOne("NetServer.Data.Models.OrdersTable", "BuyOrder")
                        .WithMany()
                        .HasForeignKey("BuyOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetServer.Data.Models.OrdersTable", "SellOrder")
                        .WithMany()
                        .HasForeignKey("SellOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BuyOrder");

                    b.Navigation("SellOrder");
                });

            modelBuilder.Entity("NetServer.Data.Models.WalletTable", b =>
                {
                    b.HasOne("NetServer.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetServer.Data.Models.WalletTable", null)
                        .WithMany("Wallets")
                        .HasForeignKey("WalletTableWalletID");
                });

            modelBuilder.Entity("NetServer.Data.Models.FeeTable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("NetServer.Data.Models.OrdersTable", b =>
                {
                    b.Navigation("OrderBook")
                        .IsRequired();
                });

            modelBuilder.Entity("NetServer.Data.Models.WalletTable", b =>
                {
                    b.Navigation("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
